### ISSUE TITLE
Subscription Element class not showing up in API docs

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-docs#1]
![image](https://user-images.githubusercontent.com/133571/68568967-eb271000-0497-11ea-81e5-d52592afd0bd.png)

**Comment by mattstein** [comment]
Building the latest current docs, I’m pretty sure the cause is this line: https://github.com/craftcms/commerce/blob/develop/src/elements/Subscription.php#L294

The clue when building is this output, which comes without any other reference:

```
 Parse Error: Syntax error, unexpected T_OBJECT_OPERATOR on line 294
```

If you just `return new DateTime();`, the page builds.

**Comment by mattstein** [comment]
Splitting that handsome one-liner into two fixes the issue with the parser:

```php
public function getTrialExpires(): DateTIme
{
    $created = clone $this->dateCreated;
    return $created->add(new DateInterval('P' . $this->trialDays . 'D'));
}
```
