### ISSUE TITLE
Docs 404 link to Craft installation instructions

### ISSUE THREAD

**Issue by khalwat** [craftcms/commerce-docs#12]
On this page:

https://github.com/craftcms/commerce-docs/blob/v2/en/installation.md

...all of the links are 404s that point to the old Craft CMS 3 github docs.

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/commerce-docs/commit/7ae36b8c1366183ffad430add44e48ad35959462

Thanks!
