### ISSUE TITLE
Issue with Customer Address Management

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce-docs#15]
These docs seem outdated for Commerce 2. Using the templates provided I'm getting a `Unable to resolve the request "commerce/customerAddresses/save"` error.

https://github.com/craftcms/commerce-docs/blob/v2/en/customer-address-management.md

**Comment by lukeholder** [comment]
Fixed in cf69c00b3ebec417718febcee78ab4820db65a62
