### ISSUE TITLE
Make it clearer the difference between price and salePrice

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-docs#18]
Across both purchasables and line items.

**Comment by lukeholder** [comment]
`price` is the original price. In the case of a variant this would be the price as entered in the Edit Product page.

`salePrice` is the price after sales have been applied to the purchasable. 

When a line item is populated by the purchasable, the `price` and `salePrice` are copied from the purchasable to the line item and the `populateLineItem` event is triggered. Developers can override the `salePrice` of the line item in this event, but it no longer represents the deduction in price due to the actual sales applied.

**Comment by mattstein** [comment]
@lukeholder Would you consider this a note to self, or a note to Matt?

**Comment by lukeholder** [comment]
@mattstein Note to us both. Lets chat.
