### ISSUE TITLE
Event OnOrderComplete

### ISSUE THREAD

**Issue by olsp** [craftcms/commerce-docs#24]
Hi,

I would like to know how I can use the OnOrderComplete Event in Commerce 2.
Since the events/hooks have changed in Craft CMS 3, I guess this is no longer valid: https://craftcommerce.com/docs/events-reference#commerce_orders.onordercomplete

In the docs for Commerce 2, I haven't found anything about it.

I would like to make a plugin which creates a CSV file when an order is made. I guess this event would be appropriate for it, wouldn't it?

**Comment by lukeholder** [comment]
Documentation of events will come with the API documentation.

Here is an example of the on complete event:
