### ISSUE TITLE
order.paymentMethodId should be order.gatewayId

### ISSUE THREAD

**Issue by levinelson** [craftcms/commerce-docs#8]
https://github.com/craftcms/commerce-docs/blob/946945ed3197da688a045f6f3e856f2110f685bc/en/order-model.md#paymentmethodid

Unless I'm misunderstanding how its meant to be used. `cart.paymentMethodId` was giving me errors, but `cart.gatewayId` got me what I was looking for.

**Comment by lukeholder** [comment]
Thanks, fixed.
